issuer: "http://localhost:5556/dex"
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]

frontend:
  dir: /web
  
telemetry:
  http: 0.0.0.0:5558

oauth2:
    # use ["code", "token", "id_token"] to enable implicit flow for web-only clients
  responseTypes: [ "code", "token", "id_token" ] # also allowed are "token" and "id_token"
    # By default, Dex will ask for approval to share data with application
    # (approval for sharing data from connected IdP to Dex is separate process on IdP)
  skipApprovalScreen: true
    # If only one authentication method is enabled, the default behavior is to
    # go directly to it. For connected IdPs, this redirects the browser away
    # from application to upstream provider such as the Google login page
#   alwaysShowLoginScreen: false
logger:
  level: "debug"
  format: "json"

staticClients:
- id: swagger-ui
  redirectURIs:
    - 'http://localhost:2027/oauth2-redirect.html'
  name: 'Cafienne Swagger UI'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
- id: case-user-interface 
  redirectURIs:
    - 'http://localhost:3317/callback'
    - 'http://localhost:4317/callback'
  name: 'Case Engine UI'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

# Let dex keep a list of passwords which can be used to login to dex.
enablePasswordDB: true

# A static list of passwords to login the end user. By identifying here, dex
# won't look in its underlying storage for passwords.
#
# If this option isn't chosen users may be added through the gRPC API.
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  userID: "admin"

- email: "lana" #email is the login name for dex;
  # bcrypt hash of the string "lana"
  hash: "$2a$10$ZrEQl/enxrc1bhDWrwhKSePYkqCEf.2X3wXeat/hI0ULOptDUpyCS"
  # userID is the account that is known and registered inside Case Engine
  userID: "lana"

- email: "lana@example.com"
  # bcrypt hash of the string "lana"
  hash: "$2a$10$ZrEQl/enxrc1bhDWrwhKSePYkqCEf.2X3wXeat/hI0ULOptDUpyCS"
  # userID is the account that is known and registered inside Case Engine
  userID: "lana"

- email: "suzy@example.com"
  # bcrypt hash of the string "suzy"
  hash: "$2a$10$3pTi1m5yR.tBcZMV/dJi.O1NlMPN/ZH03eSmNfJFuTOOTm82T03lK"
  # userID is the account that is known and registered inside Case Engine
  userID: "suzy"

- email: "suzy"
  # bcrypt hash of the string "suzy"
  hash: "$2a$10$3pTi1m5yR.tBcZMV/dJi.O1NlMPN/ZH03eSmNfJFuTOOTm82T03lK"
  # userID is the account that is known and registered inside Case Engine
  userID: "suzy"

- email: "hank@example.com"
  # bcrypt hash of the string "hank"
  hash: "$2a$10$osTMgQ8GxoeWghmYcrBXB.0nV9XsoQkAMUcNlL0/wT7qYoJSnbJzS"
  # userID is the account that is known and registered inside Case Engine
  userID: "hank"

- email: "hank"
  # bcrypt hash of the string "hank"
  hash: "$2a$10$osTMgQ8GxoeWghmYcrBXB.0nV9XsoQkAMUcNlL0/wT7qYoJSnbJzS"
  # userID is the account that is known and registered inside Case Engine
  userID: "hank"

- email: "sending-user@example.com"
  # bcrypt hash of the string "suzy"
  hash: "$2a$10$3pTi1m5yR.tBcZMV/dJi.O1NlMPN/ZH03eSmNfJFuTOOTm82T03lK"
  # userID is the account that is known and registered inside Case Engine
  userID: "sender"

- email: "receiving-user@example.com"
  # bcrypt hash of the string "suzy"
  hash: "$2a$10$3pTi1m5yR.tBcZMV/dJi.O1NlMPN/ZH03eSmNfJFuTOOTm82T03lK"
  # userID is the account that is known and registered inside Case Engine
  userID: "receiver"

- email: "sender"
  # bcrypt hash of the string "suzy"
  hash: "$2a$10$3pTi1m5yR.tBcZMV/dJi.O1NlMPN/ZH03eSmNfJFuTOOTm82T03lK"
  # userID is the account that is known and registered inside Case Engine
  userID: "sending-user"

- email: "receiver"
  # bcrypt hash of the string "suzy"
  hash: "$2a$10$3pTi1m5yR.tBcZMV/dJi.O1NlMPN/ZH03eSmNfJFuTOOTm82T03lK"
  # userID is the account that is known and registered inside Case Engine
  userID: "receiving-user"

- email: "employee"
  # bcrypt hash of the string "suzy"
  hash: "$2a$10$3pTi1m5yR.tBcZMV/dJi.O1NlMPN/ZH03eSmNfJFuTOOTm82T03lK"
  # userID is the account that is known and registered inside Case Engine
  userID: "employee"

